datasource:
  url: jdbc:mysql://localhost:3306/simple
  username: root
  password: test

  slave:
    slave1:
      url: jdbc:mysql://localhost:3307/simple
      name: slave-db


spring:
  jpa:
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show_sql: false
        generate-ddl: false
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true